version: '3'
services:
  python-gpu:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - CUDA_VERSION=${CUDA_VERSION}
    volumes:
      - ".:/workspace"
      - ".jupyter:/root/.jupyter"
    deploy:
      resources:
        reservations:
          devices:
            - 'driver': 'nvidia'
              'capabilities': [ 'gpu' ]
    # runtime: nvidia
    tty: true
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "${JUPYTER_PORT}:8888"
    command: jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8888
