version: '3'
services:
  frontend-st:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - ".:/workspace"
    tty: true
    ports:
      - "${STREAMLIT_PORT}:5678"
