version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    container_name: backend
    volumes:
      - ".:/workspace"
    tty: true
    ports:
      - "${FASTAPI_PORT}:8000"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
